# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentsummons < Formula
  desc "Invoke agent harnesses (Antigravity CLI, Claude Code, Codex CLI) headlessly"
  homepage "https://github.com/agent-ecosystem/agentsummons"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-ecosystem/agentsummons/releases/download/v0.1.0/agentsummons_0.1.0_darwin_amd64.tar.gz"
      sha256 "1bde91956112ed4b92f9a5925575de5288e6b419b9e4cee1f6d751574687a7b1"

      define_method(:install) do
        bin.install "agentsummons"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-ecosystem/agentsummons/releases/download/v0.1.0/agentsummons_0.1.0_darwin_arm64.tar.gz"
      sha256 "88b904925d27b94ec062b8dc6f610ced49332abc7a0a2e419182d22fe87877bc"

      define_method(:install) do
        bin.install "agentsummons"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/agentsummons/releases/download/v0.1.0/agentsummons_0.1.0_linux_amd64.tar.gz"
      sha256 "52fa7e4c8ad08ba8f0b81b5ce8755777e283320acbce1cdeadbb665f8eec018b"
      define_method(:install) do
        bin.install "agentsummons"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/agentsummons/releases/download/v0.1.0/agentsummons_0.1.0_linux_arm64.tar.gz"
      sha256 "157ea31bf0363d000ebc34418a5ee8a0e1d95c2cd53c33170cb24e0a50c0aa7c"
      define_method(:install) do
        bin.install "agentsummons"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentsummons --version")
  end
end
