# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentminutes < Formula
  desc "Parse agent harness session logs (Antigravity CLI, Claude Code, Codex CLI) into a unified event schema"
  homepage "https://github.com/agent-ecosystem/agentminutes"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-ecosystem/agentminutes/releases/download/v0.3.1/agentminutes_0.3.1_darwin_amd64.tar.gz"
      sha256 "a6f98cdbe65c0be42e72a5329ff5bd3230261c44f0324733a4d1adc808ded727"

      define_method(:install) do
        bin.install "agentminutes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-ecosystem/agentminutes/releases/download/v0.3.1/agentminutes_0.3.1_darwin_arm64.tar.gz"
      sha256 "6d5b2f9d1ac236d5513bdec8f1ece6157cd7905209a241f516ac5d5c39bc0c8b"

      define_method(:install) do
        bin.install "agentminutes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/agentminutes/releases/download/v0.3.1/agentminutes_0.3.1_linux_amd64.tar.gz"
      sha256 "4c7d3382b5ef3cb421c14fac5912329b95dc0d2dcc16b7dcd2cd5c073196e27f"
      define_method(:install) do
        bin.install "agentminutes"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/agentminutes/releases/download/v0.3.1/agentminutes_0.3.1_linux_arm64.tar.gz"
      sha256 "2ed09889afa13509396d686eab238ea4a849eef6fcc402f48adb1dcc8b246971"
      define_method(:install) do
        bin.install "agentminutes"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentminutes --version")
  end
end
