# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentminutes < Formula
  desc "Parse agent harness session logs (Antigravity CLI, Claude Code, Codex CLI, GitHub Copilot CLI) into a unified event schema"
  homepage "https://github.com/agent-ecosystem/agentminutes"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-ecosystem/agentminutes/releases/download/v0.6.0/agentminutes_0.6.0_darwin_amd64.tar.gz"
      sha256 "6e958ec0b1cb166f96ce0ba861a260aa7936a8fd06a381110825a6d684e4b48e"

      define_method(:install) do
        bin.install "agentminutes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-ecosystem/agentminutes/releases/download/v0.6.0/agentminutes_0.6.0_darwin_arm64.tar.gz"
      sha256 "8425d915e167520c9a355eceebd6b51bae0ff8a5c9c952a55e0510e9036eec29"

      define_method(:install) do
        bin.install "agentminutes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/agentminutes/releases/download/v0.6.0/agentminutes_0.6.0_linux_amd64.tar.gz"
      sha256 "67d8d86ad6dc2fb339dfff1698a64db4b2f69c50382b70bdd3495a655de75796"
      define_method(:install) do
        bin.install "agentminutes"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/agentminutes/releases/download/v0.6.0/agentminutes_0.6.0_linux_arm64.tar.gz"
      sha256 "0198314f0c9868c3364c63553d350df579b9db5fe7b994c31efd43385b0d135b"
      define_method(:install) do
        bin.install "agentminutes"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentminutes --version")
  end
end
