# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentsummons < Formula
  desc "Invoke agent harnesses (Antigravity CLI, Claude Code, Codex CLI) headlessly"
  homepage "https://github.com/agent-ecosystem/agentsummons"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-ecosystem/agentsummons/releases/download/v0.2.2/agentsummons_0.2.2_darwin_amd64.tar.gz"
      sha256 "54ad3df57a1d3918736f60345e80befa54d56d75de845b2b192612e03bb5add1"

      define_method(:install) do
        bin.install "agentsummons"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-ecosystem/agentsummons/releases/download/v0.2.2/agentsummons_0.2.2_darwin_arm64.tar.gz"
      sha256 "6e40b59b73c5cb55179b1e5f05aa9cacce6bd1046092ff049abb931cf8f1d8d5"

      define_method(:install) do
        bin.install "agentsummons"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/agentsummons/releases/download/v0.2.2/agentsummons_0.2.2_linux_amd64.tar.gz"
      sha256 "30d6cf200f3067224e44421dc684a40f21b35509fcfef54cad3f9f46d764e66f"
      define_method(:install) do
        bin.install "agentsummons"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/agentsummons/releases/download/v0.2.2/agentsummons_0.2.2_linux_arm64.tar.gz"
      sha256 "f0e5ce5546f696f0082b77601266f927348db3931bbded87995ac7fb99561006"
      define_method(:install) do
        bin.install "agentsummons"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agentsummons --version")
  end
end
