# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkillValidator < Formula
  desc "CLI tool that validates and scores Agent Skill packages"
  homepage "https://github.com/agent-ecosystem/skill-validator"
  version "1.5.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-ecosystem/skill-validator/releases/download/v1.5.4/skill-validator_1.5.4_darwin_amd64.tar.gz"
      sha256 "e8cd60ecbdda3074011b92fb2b88f0ad8692df617530c66048f2c9e01b0f7e85"

      define_method(:install) do
        bin.install "skill-validator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-ecosystem/skill-validator/releases/download/v1.5.4/skill-validator_1.5.4_darwin_arm64.tar.gz"
      sha256 "42bee9c3b39b1b7306dc240e2647b2a030768e167688ae401d13095f80382264"

      define_method(:install) do
        bin.install "skill-validator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skill-validator/releases/download/v1.5.4/skill-validator_1.5.4_linux_amd64.tar.gz"
      sha256 "587c9b3bf5dc376f630e01806f4a3f34f20d7fa931e3e6628557413aefb4e6f3"
      define_method(:install) do
        bin.install "skill-validator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skill-validator/releases/download/v1.5.4/skill-validator_1.5.4_linux_arm64.tar.gz"
      sha256 "75f43a4e5891d9e41a6b485f469b501853d33678c052b7f9cbdf184f14dc1d4d"
      define_method(:install) do
        bin.install "skill-validator"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skill-validator --version")
  end
end
