# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillxp < Formula
  desc "Observe how agent harnesses load and activate Agent Skills, with transcript evidence"
  homepage "https://github.com/agent-ecosystem/skillxp"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.1.3/skillxp_0.1.3_darwin_amd64.tar.gz"
      sha256 "287262ae8c71271d7f10ee25fb4ccc8937002a47494851627d6301ecf674e95c"

      define_method(:install) do
        bin.install "skillxp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.1.3/skillxp_0.1.3_darwin_arm64.tar.gz"
      sha256 "22668fdb699d88e4996a0e8d912213df1f51aefbf867829f25473e0fec216021"

      define_method(:install) do
        bin.install "skillxp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.1.3/skillxp_0.1.3_linux_amd64.tar.gz"
      sha256 "25ea9a0db53a3065ce6051a9e9658c9fef9c062cdd74aee07d8b2e693a2c6d71"
      define_method(:install) do
        bin.install "skillxp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.1.3/skillxp_0.1.3_linux_arm64.tar.gz"
      sha256 "53181396e4952064256eeb08d208e35b63c43386cb2e9ce40ec2d6dc3481650f"
      define_method(:install) do
        bin.install "skillxp"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skillxp --version")
  end
end
