# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillxp < Formula
  desc "Observe how agent harnesses load and activate Agent Skills, with transcript evidence"
  homepage "https://github.com/agent-ecosystem/skillxp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.1.0/skillxp_0.1.0_darwin_amd64.tar.gz"
      sha256 "3c06edf03ffb0dc920f5f13dc2cff206b7d0106f9eb55a89de215294f01cb97d"

      define_method(:install) do
        bin.install "skillxp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.1.0/skillxp_0.1.0_darwin_arm64.tar.gz"
      sha256 "b52b442b5cea39019569ebf58849047d972fe04b1e8f3bfb3ca6222807204e2c"

      define_method(:install) do
        bin.install "skillxp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.1.0/skillxp_0.1.0_linux_amd64.tar.gz"
      sha256 "f156610bc830001a271f07dfb473f5ca7883d78f5ac0e8a8232d251802aaffcf"
      define_method(:install) do
        bin.install "skillxp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.1.0/skillxp_0.1.0_linux_arm64.tar.gz"
      sha256 "4ba3a305640f8bc7a18953697ac2cd5e602093fbc233464f1da20a1bb0ec13da"
      define_method(:install) do
        bin.install "skillxp"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skillxp --version")
  end
end
