# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillxp < Formula
  desc "Observe how agent harnesses load and activate Agent Skills, with transcript evidence"
  homepage "https://github.com/agent-ecosystem/skillxp"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.4.0/skillxp_0.4.0_darwin_amd64.tar.gz"
      sha256 "45961b85d16dc2338781a2132c599af3d58db2e86ded346a04276c7bcd49a46c"

      define_method(:install) do
        bin.install "skillxp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.4.0/skillxp_0.4.0_darwin_arm64.tar.gz"
      sha256 "c9a013abec6149c18f4b211206666c26ab36ce71a4b89e7b5284b04e63de7731"

      define_method(:install) do
        bin.install "skillxp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.4.0/skillxp_0.4.0_linux_amd64.tar.gz"
      sha256 "dba0949c955d93111d86fd6d11ea1e024d3cc76ad91a9d6b89247d1f9d2c8ae5"
      define_method(:install) do
        bin.install "skillxp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skillxp/releases/download/v0.4.0/skillxp_0.4.0_linux_arm64.tar.gz"
      sha256 "260af85eb86742caea41e0fd0fb41d5b2f7444d6ae12cf8b7c51527db5666817"
      define_method(:install) do
        bin.install "skillxp"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skillxp --version")
  end
end
