# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkillValidator < Formula
  desc "CLI tool that validates and scores Agent Skill packages"
  homepage "https://github.com/agent-ecosystem/skill-validator"
  version "1.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-ecosystem/skill-validator/releases/download/v1.5.3/skill-validator_1.5.3_darwin_amd64.tar.gz"
      sha256 "a7a3556297ae6b4633c8371cd9ae56a4a5577a9110d3c04cb23a6899dc500d87"

      define_method(:install) do
        bin.install "skill-validator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-ecosystem/skill-validator/releases/download/v1.5.3/skill-validator_1.5.3_darwin_arm64.tar.gz"
      sha256 "0a50628495c3f01163c6fc26ea0f6eedbb13993f542e3dccfc0bd438e5ef15e8"

      define_method(:install) do
        bin.install "skill-validator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skill-validator/releases/download/v1.5.3/skill-validator_1.5.3_linux_amd64.tar.gz"
      sha256 "b9dbe61129e5a66aad9cf680a9b32eeb9e37736828334c255db12c1ede4d8c5b"
      define_method(:install) do
        bin.install "skill-validator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skill-validator/releases/download/v1.5.3/skill-validator_1.5.3_linux_arm64.tar.gz"
      sha256 "2716e7bbecc34bb72486d9949b46b5cb0f6a118c030c23b1c6b49ce44470b8bd"
      define_method(:install) do
        bin.install "skill-validator"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skill-validator --version")
  end
end
