# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SkillValidatorEnt < Formula
  desc "Enterprise CLI for validating and scoring Agent Skill packages via AWS Bedrock"
  homepage "https://github.com/agent-ecosystem/skill-validator-ent"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agent-ecosystem/skill-validator-ent/releases/download/v1.0.0/skill-validator-ent_1.0.0_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER"

      define_method(:install) do
        bin.install "skill-validator-ent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agent-ecosystem/skill-validator-ent/releases/download/v1.0.0/skill-validator-ent_1.0.0_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER"

      define_method(:install) do
        bin.install "skill-validator-ent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skill-validator-ent/releases/download/v1.0.0/skill-validator-ent_1.0.0_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER"
      define_method(:install) do
        bin.install "skill-validator-ent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agent-ecosystem/skill-validator-ent/releases/download/v1.0.0/skill-validator-ent_1.0.0_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER"
      define_method(:install) do
        bin.install "skill-validator-ent"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skill-validator-ent --version")
  end
end
